// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawsgbYFSgIOQFY_9PPmOVonRpofA1o0U',
    appId: '1:278530330896:web:f53685b522b85025751595',
    messagingSenderId: '278530330896',
    projectId: 'student-attandance-7aa3a',
    authDomain: 'student-attandance-7aa3a.firebaseapp.com',
    storageBucket: 'student-attandance-7aa3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3BWh7ppWjMoZ5IN6VY01T0I90B9UvoI8',
    appId: '1:278530330896:android:a45777f062783dd9751595',
    messagingSenderId: '278530330896',
    projectId: 'student-attandance-7aa3a',
    storageBucket: 'student-attandance-7aa3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFhy-13bMtjx0HRj7xo-3sC9yp_XrnK80',
    appId: '1:278530330896:ios:890b4f70f067ad41751595',
    messagingSenderId: '278530330896',
    projectId: 'student-attandance-7aa3a',
    storageBucket: 'student-attandance-7aa3a.firebasestorage.app',
    iosBundleId: 'com.example.studentsAttendanceWithMlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFhy-13bMtjx0HRj7xo-3sC9yp_XrnK80',
    appId: '1:278530330896:ios:890b4f70f067ad41751595',
    messagingSenderId: '278530330896',
    projectId: 'student-attandance-7aa3a',
    storageBucket: 'student-attandance-7aa3a.firebasestorage.app',
    iosBundleId: 'com.example.studentsAttendanceWithMlkit',
  );

}